<?php
return [
    [
        'class_name' => 'App\Models\Role',
        'field_name' => 'name',
        'values' => [
            'dev-super',
            'dev-normal',
            'admin-super',
            'admin-normal',
            'user-super',
            'user-normal',
        ],
    ],
    [
        'class_name' => 'App\Models\Permission',
        'field_name' => 'name',
        'values' => [
            'users_create',
            'users_read',
            'users_update',
            'users_delete',
            'roles_create',
            'roles_read',
            'roles_update',
            'roles_delete',
            'permissions_create',
            'permissions_read',
            'permissions_update',
            'permissions_delete',
            'tasks_create',
            'tasks_read',
            'tasks_update',
            'tasks_delete',
            'task_types_create',
            'task_types_read',
            'task_types_update',
            'task_types_delete',
            'notifications_create',
            'notifications_read',
            'notifications_update',
            'notifications_delete',
            'notification_types_create',
            'notification_types_read',
            'notification_types_update',
            'notification_types_delete',
            'settings_create',
            'settings_read',
            'settings_update',
            'settings_delete',
        ],
    ],
];